name: markasten
description: A Zettlekasten toolkit for Markdown files
inputs:
  image:
    default: "andykuszyk/markasten:latest"
    description: "The Markasten Docker image/tag to use"
  command:
    default: "tags"
    required: true
    description: "The markasten command to run in the action"
  additionalArgs:
    default: ""
    description: "Any additional markasten arguments to specify"
  input:
    required: true
    description: "The input directory"
  output:
    required: true
    description: "The output file name or directory"
runs:
  using: "composite"
  steps:
    - run: docker run -v "$(pwd)":/input -v "$(pwd)":/output ${{ inputs.image }} markasten ${{ inputs.command }} -i /input/${{ inputs.input }} -o /output/${{ inputs.output }}
      shell: bash
