name: docs
on: workflow_dispatch
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andykuszyk/markasten@master
        with:
          command: "tags"
          input: "docs/"
          output: "docs/INDEX.md"
          additionalArgs: "--capitalize --wiki-links"
      - run: cat docs/INDEX.md
