name: release
on:
  release:
    types:
      - published
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - run: make test
      - run: make build
      - run: echo docker publish
