name: docs
on: gollum
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andykuszyk/markasten@master
        with:
          command: "tags"
          input: "./"
          output: "./INDEX.md"
          additionalArgs: "--capitalize --wiki-links"
      - run: cat INDEX.md
      - run: git diff
